
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDknoWNjqqpY0Vk_wboP3nHDxFXPPIlSQ',
    appId: '1:580124483996:android:2a98869823d4098db2a859',
    messagingSenderId: '580124483996',
    projectId: 'ijobhunt-30fdc',
    storageBucket: 'ijobhunt-30fdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwClsq8SaenDREkLQVHl7-tE9WvNDbSg',
    appId: '1:580124483996:ios:cd8a43cb2bef9cbdb2a859',
    messagingSenderId: '580124483996',
    projectId: 'ijobhunt-30fdc',
    storageBucket: 'ijobhunt-30fdc.appspot.com',
    iosClientId: '580124483996-h6k6s90p0uie274sf1r98jt01fisms31.apps.googleusercontent.com',
    iosBundleId: 'com.tucimar.ijobhunts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwClsq8SaenDREkLQVHl7-tE9WvNDbSg',
    appId: '1:580124483996:ios:cd8a43cb2bef9cbdb2a859',
    messagingSenderId: '580124483996',
    projectId: 'ijobhunt-30fdc',
    storageBucket: 'ijobhunt-30fdc.appspot.com',
    iosClientId: '580124483996-h6k6s90p0uie274sf1r98jt01fisms31.apps.googleusercontent.com',
    iosBundleId: 'com.tucimar.ijobhunts',
  );

}